#!/usr/bin/env bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y python3-pip
sudo apt-get install -y npm
sudo apt-get install -y node-less
sudo npm install -y -g less
sudo npm install -y -g less-plugin-clean-css
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo apt-get install postgresql
