#!/usr/bin/env bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y python3-pip
sudo apt-get install -y npm
sudo apt-get install -y node-less
sudo npm install -y -g less
sudo npm install -y -g less-plugin-clean-css
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo apt-get install postgresql
sudo wget https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
sudo cp /usr/local/bin/wkhtmltopdf /usr/bin
sudo cp /usr/local/bin/wkhtmltoimage /usr/bin
sudo apt-get install libxslt1-dev
sudo apt-get install libldap2-dev
sudo apt-get install libsasl2-dev
sudo pip3 install phonenumbers
sudo pip3 install pyOpenSSL
sudo apt-get install fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei ttf-wqy-zenhei
fc-cache -f -v
sudo apt-get -f install
sudo apt-get install python3-pypdf2
sudo apt-get install python3-werkzeug
sudo apt-get install python3-dateutil
sudo apt-get install python3-yaml
sudo apt-get install python3-reportlab
sudo apt-get install python3-suds
sudo apt-get -f install
sudo apt-get install python3-lxml
sudo pip3 install psutil
sudo pip3 install html2text
sudo pip3 install passlib
sudo pip3 install psycopg2
sudo pip3 install psycopg2-binary
sudo pip3 install xlrd
sudo pip3 install xlwt
sudo apt-get install git
sudo git clone https://github.com/odoo/odoo.git -b 11.0 --depth=1 /wpluserp/ent
sudo pip3 install -r /opt/odoo/requirements.txt
sudo pip3 install -r /opt/odoo/doc/requirements.txt
sudo git clone https://github.com/odoo/enterprise.git -b 11.0 --depth=1 /wpluserp/ent/enterprise
sudo git clone https://wantech.visualstudio.com/W%20Plus/_git/odoo_wantech_icons /auto/wantech/odooicons/
sudo cp -r /auto/wantech/odooicons/addons /wpluserp/ent/
sudo cp -r /auto/wantech/odooicons/odoo /wpluserp/ent/
sudo mkdir /wpluserp/ent/w_clients
sudo mkdir /wpluserp/ent/w_common
sudo mkdir /wpluserp/ent/w_config
sudo mkdir /wpluserp/ent/w_editions
sudo git clone https://wantech.visualstudio.com/Dev%20Team/_git/wantech_modules /wpluserp/ent/w_common
